baseURL = 'https://dknelson.dev'
languageCode = 'en-us'
title = 'dknelson.dev'
theme = 're-terminal'

[params]
  contentTypeName = "posts"
  # orange, blue, red, green, pink, or paper
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = true
  # favicon = "favicon.ico"

[languages]
  [languages.en.params]
    title = "dknelson.dev"
    [languages.en.params.logo]
      logoText = "dknelson.dev"
      logoHomeLink = "/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
